twig:
    file_name_pattern: '*.twig'
    globals:
        recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        barion_pixel_id: '%env(BARION_PIXEL_ID)%'
        google_tag_manager_id: '%env(GOOGLE_TAG_MANAGER_ID)%'

when@test:
    twig:
        strict_variables: true
