INSERT INTO `packages` (`id`, `level`, `title`, `price`, `features`)
VALUES (1, 'beginner', 'Alap', 8900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (2, 'beginner', 'Prémium', 9900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","3 módosítási lehetőség"]'),
       (3, 'beginner', 'Prémium+', 10900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","15 sablonválasztási lehetőség","48 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","Korlátlan módosítási lehetőség"]'),
       (4, 'beginner', 'Angol', 11900,
        '["Angol nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (5, 'beginner', 'Angol-Magyar', 13900,
        '["Angol és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (6, 'beginner', 'Német', 12900,
        '["Német nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (7, 'beginner', 'Német-Magyar', 14900,
        '["Német és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (8, 'junior', 'Alap', 11900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (9, 'junior', 'Prémium', 13900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","3 módosítási lehetőség"]'),
       (10, 'junior', 'Prémium+', 14900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","15 sablonválasztási lehetőség","48 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","Korlátlan módosítási lehetőség"]'),
       (11, 'junior', 'Angol', 14900,
        '["Angol nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (12, 'junior', 'Angol-Magyar', 16900,
        '["Angol és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (13, 'junior', 'Német', 14900,
        '["Német nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (14, 'junior', 'Német-Magyar', 17900,
        '["Német és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (15, 'medior', 'Alap', 15900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (16, 'medior', 'Prémium', 16900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","3 módosítási lehetőség"]'),
       (17, 'medior', 'Prémium+', 17900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","15 sablonválasztási lehetőség","48 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","Korlátlan módosítási lehetőség"]'),
       (18, 'medior', 'Angol', 18900,
        '["Angol nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (19, 'medior', 'Angol-Magyar', 20900,
        '["Angol és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (20, 'medior', 'Német', 19900,
        '["Német nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (21, 'medior', 'Német-Magyar', 22900,
        '["Német és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (22, 'senior', 'Alap', 8900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (23, 'senior', 'Prémium', 9900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","3 módosítási lehetőség"]'),
       (24, 'senior', 'Prémium+', 10900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","15 sablonválasztási lehetőség","48 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","Korlátlan módosítási lehetőség"]'),
       (25, 'senior', 'Angol', 11900,
        '["Angol nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (26, 'senior', 'Angol-Magyar', 13900,
        '["Angol és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (27, 'senior', 'Német', 12900,
        '["Német nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (28, 'senior', 'Német-Magyar', 14900,
        '["Német és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (29, 'leader', 'Alap', 8900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (30, 'leader', 'Prémium', 9900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","3 módosítási lehetőség"]'),
       (31, 'leader', 'Prémium+', 10900,
        '["Személyre szabott önéletrajz","Kulcsszó optimalizálás (ATS barát)","15 sablonválasztási lehetőség","48 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","Korlátlan módosítási lehetőség"]'),
       (32, 'leader', 'Angol', 11900,
        '["Angol nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (33, 'leader', 'Angol-Magyar', 13900,
        '["Angol és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (34, 'leader', 'Német', 12900,
        '["Német nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","10 sablonválasztási lehetőség","72 órán belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]'),
       (35, 'leader', 'Német-Magyar', 14900,
        '["Német és magyar nyelvű önéletrajz","Személyre szabott","Kulcsszó optimalizálás (ATS barát)","5 sablonválasztási lehetőség","5 munkanapon belüli kézbesítés","Telefonos vagy emailes konzultáció","1 módosítási lehetőség"]');
